package agent

import (
	"context"
	"errors"
	"strings"
	"sync"
	"time"

	"github.com/thevibeworks/deepseek-pi/ai"
)

// ErrBusy is returned by Prompt while a run is already in flight. Mid-run input
// belongs in Steer or FollowUp, which have defined injection points; starting a
// second run against the same transcript does not.
var ErrBusy = errors.New("agent is already running: use Steer or FollowUp")

// QueueMode controls how many queued messages are drained at once.
type QueueMode string

const (
	// QueueOneAtATime injects the oldest queued message and leaves the rest.
	// Default, because it gives the model a chance to react to each redirect
	// instead of receiving a wall of instructions at once.
	QueueOneAtATime QueueMode = "one-at-a-time"
	// QueueAll injects everything queued at the next drain point.
	QueueAll QueueMode = "all"
)

// Agent owns a transcript and runs the loop against it.
//
// It adds three things over the bare loop: the steering and follow-up queues,
// the session-level retry layer, and the mutual exclusion that stops two runs
// from interleaving on one transcript.
type Agent struct {
	mu      sync.Mutex
	ctx     *Context
	cfg     LoopConfig
	stream  ai.StreamFunc
	running bool

	steering  []ai.Message
	followUps []ai.Message
	queueMode QueueMode

	// Retry is the session-level retry policy: it replays a whole turn when a
	// run ends in a transient provider failure.
	Retry SessionRetry

	subscribers []Sink
}

// SessionRetry replays turns that failed for transient reasons.
//
// This is the layer that matters. It sees the transcript, so it can pop the
// failed assistant message and continue from a clean tail — something a
// transport-level retry cannot do, because by then tokens have already been
// generated and billed.
type SessionRetry struct {
	// MaxAttempts is how many times a run may be replayed. Zero disables it.
	MaxAttempts int
	// BaseDelay doubles per attempt.
	BaseDelay time.Duration
}

// DefaultSessionRetry is 3 attempts starting at 2s, matching pi.
func DefaultSessionRetry() SessionRetry {
	return SessionRetry{MaxAttempts: 3, BaseDelay: 2 * time.Second}
}

// New creates an agent over a context.
func New(c *Context, cfg LoopConfig, stream ai.StreamFunc) *Agent {
	return &Agent{
		ctx:       c,
		cfg:       cfg,
		stream:    stream,
		queueMode: QueueOneAtATime,
		Retry:     DefaultSessionRetry(),
	}
}

// Subscribe registers an event sink for every run.
func (a *Agent) Subscribe(s Sink) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.subscribers = append(a.subscribers, s)
}

// SetQueueMode changes the drain policy for both queues.
func (a *Agent) SetQueueMode(m QueueMode) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.queueMode = m
}

// Context exposes the live context. Callers must not mutate it during a run.
func (a *Agent) Context() *Context { return a.ctx }

// Config returns a copy of the current loop config.
func (a *Agent) Config() LoopConfig {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.cfg
}

// SetModel changes the model for subsequent turns.
//
// A transcript is pinned to one model for its lifetime by convention: nothing
// verifies that thinking blocks generated by flash replay correctly under pro,
// and assuming it works is how a harness produces silently degraded turns.
// Crossing models should mean a new context.
func (a *Agent) SetModel(model string) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.cfg.Model = model
}

// SetEffort changes the reasoning level for subsequent turns.
func (a *Agent) SetEffort(e ai.Effort) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.cfg.Effort = e
}

// Running reports whether a run is in flight.
func (a *Agent) Running() bool {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.running
}

// Steer queues a message for injection at the next turn boundary of the
// running loop. If no run is active it will be picked up by the next one.
func (a *Agent) Steer(msg ai.Message) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.steering = append(a.steering, msg)
}

// FollowUp queues a message to be processed after the agent would otherwise
// stop, keeping the run going instead of ending it.
func (a *Agent) FollowUp(msg ai.Message) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.followUps = append(a.followUps, msg)
}

// Pending reports how many messages are queued.
func (a *Agent) Pending() (steering, followUps int) {
	a.mu.Lock()
	defer a.mu.Unlock()
	return len(a.steering), len(a.followUps)
}

func (a *Agent) drain(queue *[]ai.Message) []ai.Message {
	a.mu.Lock()
	defer a.mu.Unlock()
	if len(*queue) == 0 {
		return nil
	}
	if a.queueMode == QueueAll {
		out := *queue
		*queue = nil
		return out
	}
	out := (*queue)[:1]
	*queue = (*queue)[1:]
	return out
}

// Prompt starts a run with a user message and blocks until it settles.
func (a *Agent) Prompt(ctx context.Context, text string) ([]ai.Message, error) {
	return a.PromptWith(ctx, ai.UserMessage(text))
}

// PromptWith starts a run with prepared messages.
func (a *Agent) PromptWith(ctx context.Context, prompts ...ai.Message) ([]ai.Message, error) {
	a.mu.Lock()
	if a.running {
		a.mu.Unlock()
		return nil, ErrBusy
	}
	a.running = true
	cfg := a.cfg
	a.mu.Unlock()

	defer func() {
		a.mu.Lock()
		a.running = false
		a.mu.Unlock()
	}()

	cfg = a.bindQueues(cfg)
	emit := a.fanout()

	produced := Run(ctx, prompts, a.ctx, cfg, a.stream, emit)
	produced = append(produced, a.retryLoop(ctx, cfg, emit)...)
	return produced, nil
}

// bindQueues wires the agent's queues into the loop config without clobbering
// hooks a caller already set.
func (a *Agent) bindQueues(cfg LoopConfig) LoopConfig {
	userSteering := cfg.GetSteeringMessages
	cfg.GetSteeringMessages = func() []ai.Message {
		msgs := a.drain(&a.steering)
		if userSteering != nil {
			msgs = append(msgs, userSteering()...)
		}
		return msgs
	}
	userFollowUp := cfg.GetFollowUpMessages
	cfg.GetFollowUpMessages = func() []ai.Message {
		msgs := a.drain(&a.followUps)
		if userFollowUp != nil {
			msgs = append(msgs, userFollowUp()...)
		}
		return msgs
	}
	return cfg
}

func (a *Agent) fanout() Sink {
	a.mu.Lock()
	subs := append([]Sink(nil), a.subscribers...)
	a.mu.Unlock()
	return func(ev Event) {
		for _, s := range subs {
			s(ev)
		}
	}
}

// retryLoop replays transient failures.
//
// The failed assistant message is popped from the CONTEXT (so the provider
// payload starts from a clean tail) but the caller still receives it in the
// returned messages, because a session log should record that the failure
// happened. Continue then resumes from the last user or tool-result message.
func (a *Agent) retryLoop(ctx context.Context, cfg LoopConfig, emit Sink) []ai.Message {
	var extra []ai.Message
	for attempt := 0; attempt < a.Retry.MaxAttempts; attempt++ {
		if ctx.Err() != nil {
			return extra
		}
		last := a.lastMessage()
		if last == nil || last.Role != ai.RoleAssistant || last.StopReason != ai.StopError {
			return extra
		}
		if !RetryableError(last.ErrorMessage) {
			return extra
		}

		// Pop the failed turn so the tail converts to a user or tool-result
		// message, which is what Continue requires.
		a.ctx.Messages = a.ctx.Messages[:len(a.ctx.Messages)-1]
		if len(a.ctx.Messages) == 0 || a.ctx.Messages[len(a.ctx.Messages)-1].Role == ai.RoleAssistant {
			return extra
		}

		delay := a.Retry.BaseDelay << attempt
		if !sleep(ctx, delay) {
			return extra
		}
		extra = append(extra, Continue(ctx, a.ctx, cfg, a.stream, emit)...)
	}
	return extra
}

func (a *Agent) lastMessage() *ai.Message {
	if len(a.ctx.Messages) == 0 {
		return nil
	}
	return &a.ctx.Messages[len(a.ctx.Messages)-1]
}

// retryableFragments are error substrings worth replaying a turn for.
var retryableFragments = []string{
	"provider error (5",
	"rate limited (429)",
	"stream ended before completion",
	"reading stream",
	"connection reset",
	"connection refused",
	"unexpected EOF",
	"EOF",
	"timeout",
	"temporarily unavailable",
	"overloaded",
	"service unavailable",
}

// fatalFragments never retry, however transient they look. Replaying a billing
// or auth failure burns wall-clock and tells the user nothing new.
var fatalFragments = []string{
	"authentication failed",
	"insufficient balance",
	"invalid_request",
	"no DeepSeek API key",
	"quota",
	"billing",
}

// RetryableError classifies an assistant error message.
//
// Fatal fragments are checked first: an "insufficient balance" response can
// arrive with a 5xx-looking wrapper, and retrying it three times just delays
// the message the user needs to see.
func RetryableError(msg string) bool {
	if msg == "" {
		return false
	}
	lower := strings.ToLower(msg)
	for _, f := range fatalFragments {
		if strings.Contains(lower, f) {
			return false
		}
	}
	for _, f := range retryableFragments {
		if strings.Contains(lower, strings.ToLower(f)) {
			return true
		}
	}
	return false
}

func sleep(ctx context.Context, d time.Duration) bool {
	if d <= 0 {
		return ctx.Err() == nil
	}
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-t.C:
		return true
	case <-ctx.Done():
		return false
	}
}
